version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/issueTree
permissions:
  - object: /home/ubuntu/issueTree/
    owner: ubuntu
    group: ubuntu
hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ubuntu
