name: Build and Deploy SpringBoot to EC2

on:
  push:
    branches: [ "main" ]
    
env:
  PROJECT_NAME: issueTree-project
  BUCKET_NAME: issuetree-cicd-bucket
  CODE_DEPLOY_APP_NAME: issueTree_codedeploy
  DEPLOYMENT_GROUP_NAME: issueTree_instance

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name : Set up ES.properites file
        run : echo "${{ secrets.DEV_ES }}" > ./src/main/resources/application-ES.properties
        shell : bash

      - name : Set up SLACK.properties file
        run : echo "${{ secrets.DEV_SLACK }}" > ./src/main/resources/application-SLACK.properties
        shell : bash

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build and Test
        run: ./gradlew build test

      - name: Make Zip File
        run: zip -qq -r ./$GITHUB_SHA.zip .
        shell: bash
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_PRIVATE_ACCESS_KEY }}
          aws-region: ap-northeast-2
      
      - name: Upload to S3
        run: |
          aws deploy push \
            --application-name ${{ env.CODE_DEPLOY_APP_NAME }} \
            --ignore-hidden-files \
            --s3-location s3://$BUCKET_NAME/$GITHUB_SHA.zip \
            --source .

      - name: Code Deploy To EC2 instance
        run: aws deploy create-deployment
                --application-name $CODE_DEPLOY_APP_NAME
                --deployment-config-name CodeDeployDefault.AllAtOnce
                --deployment-group-name $DEPLOYMENT_GROUP_NAME
                --s3-location bucket=$BUCKET_NAME,bundleType=zip,key=$GITHUB_SHA.zip
